<a href="https://colab.research.google.com/github/ZohrehFeridoun/RL_ex4/blob/main/RL_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gym
import numpy as np
import random

env = gym.make('FrozenLake8x8-v1')

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [ ]:
q_table = np.zeros((env.observation_space.n, env.action_space.n))

In [ ]:
def reward(state, action, next_state):
    if next_state == env.observation_space.n - 1:
        return 1
    else:
        return 0

In [ ]:
def sarsa(env, num_episodes, alpha, gamma, epsilon):
    for i in range(num_episodes):
        state = env.reset()
        action = get_action(state, epsilon, q_table)
        done = False
        while not done:
            next_state, reward_i, done, _ = env.step(action)
            next_action = get_action(next_state, epsilon, q_table)
            td_target = reward_i + gamma * q_table[next_state][next_action]
            td_error = td_target - q_table[state][action]
            q_table[state][action] += alpha * td_error
            state = next_state
            action = next_action
            reward_total = reward_i
        print(f"Episode {i+1}: Reward = {reward_total}")

In [ ]:
def get_action(state, epsilon, q_table):
    if random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(q_table[state])
    return action

In [ ]:
num_episodes = 10000
alpha = 0.1
gamma = 0.99
epsilon = 0.05

sarsa(env, num_episodes, alpha, gamma, epsilon)

Streaming output truncated to the last 5000 lines.
Episode 5001: Reward = 0.0
Episode 5002: Reward = 0.0
Episode 5003: Reward = 0.0
Episode 5004: Reward = 0.0
Episode 5005: Reward = 0.0
Episode 5006: Reward = 0.0
Episode 5007: Reward = 0.0
Episode 5008: Reward = 0.0
Episode 5009: Reward = 0.0
Episode 5010: Reward = 0.0
Episode 5011: Reward = 0.0
Episode 5012: Reward = 0.0
Episode 5013: Reward = 0.0
Episode 5014: Reward = 0.0
Episode 5015: Reward = 0.0
Episode 5016: Reward = 0.0
Episode 5017: Reward = 0.0
Episode 5018: Reward = 0.0
Episode 5019: Reward = 0.0
Episode 5020: Reward = 0.0
Episode 5021: Reward = 0.0
Episode 5022: Reward = 0.0
Episode 5023: Reward = 0.0
Episode 5024: Reward = 0.0
Episode 5025: Reward = 0.0
Episode 5026: Reward = 0.0
Episode 5027: Reward = 0.0
Episode 5028: Reward = 0.0
Episode 5029: Reward = 0.0
Episode 5030: Reward = 0.0
Episode 5031: Reward = 0.0
Episode 5032: Reward = 0.0
Episode 5033: Reward = 0.0
Episode 5034: Reward = 0.0
Episode 5035: Reward = 0.0
Epis

In [ ]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
n p.argmax(q_table[0])

0